steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/DevOps-Project3/gke-repo/quickstart-image', './app1' ]
  id: 'Build Docker Image'

  # images:
  # - 'asia-docker.pkg.dev/DevOps-Project3/gke-repo/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/DevOps-Project3/gke-repo/quickstart-image' ]
  id: 'Push Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/DevOps-Project3/gke-repo/flask-image', './app2' ]
  id: 'Build Docker Image2'

  # images:
  # - 'asia-docker.pkg.dev/DevOps-Project3/gke-repo/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/DevOps-Project3/gke-repo/flask-image' ]
  id: 'Push Docker Image2'


- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=asia-south1
    gcloud deploy apply --file deploy/dev.yaml --region=asia-south1
    gcloud deploy apply --file deploy/prod.yaml --region=asia-south2

    gcloud deploy releases create 'app1-release-${SHORT_SHA}' --delvery-pipeline=gke-cicd-pipeline --region=asia-south1 --from-k8s-manifest=./kubernetes/app.yaml
    gcloud deploy releases create 'app2-release-${SHORT_SHA}' --delvery-pipeline=gke-cicd-pipeline --region=asia-south2 --from-k8s-manifest=./kubernetes/app2.yaml

options:
  logging: CLOUD_LOGGING_ONLY
